export const TRIGGER_WEBHOOKS_ROUTE_BASE_PATH = "/v1/triggers/webhooks";

export const TriggerWebhooksBadRequestCodes = {
  INVALID_WEBHOOK_SOURCE_REFERENCE: "INVALID_WEBHOOK_SOURCE_REFERENCE",
  INVALID_WEBHOOK_TRIGGER_REQUIREMENTS: "INVALID_WEBHOOK_TRIGGER_REQUIREMENTS",
  WEBHOOK_SOURCE_TARGET_NOT_WEBHOOK_CAPABLE: "WEBHOOK_SOURCE_TARGET_NOT_WEBHOOK_CAPABLE",
  INVALID_SANDBOX_PROFILE_REFERENCE: "INVALID_SANDBOX_PROFILE_REFERENCE",
  INVALID_SANDBOX_PROFILE_TRIGGER_REFERENCE: "INVALID_SANDBOX_PROFILE_TRIGGER_REFERENCE",
  INVALID_PRIMARY_REPOSITORY: "INVALID_PRIMARY_REPOSITORY",
  INVALID_WEBHOOK_TRIGGER_TEMPLATE_REFERENCES: "INVALID_WEBHOOK_TRIGGER_TEMPLATE_REFERENCES",
} as const;
